// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelManagment.Domain.Models;

public partial class Booking
{
    public int BookingId { get; set; }

    public int GuestId { get; set; }

    public int RoomId { get; set; }

    public DateOnly CheckIn { get; set; }

    public DateOnly CheckOut { get; set; }

    public string Status { get; set; }

    public decimal? TotalAmount { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<FacilityBooking> FacilityBookings { get; set; } = new List<FacilityBooking>();

    public virtual Guest Guest { get; set; }

    public virtual ICollection<GuestReview> GuestReviews { get; set; } = new List<GuestReview>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Room Room { get; set; }

    public virtual ICollection<RoomServiceRequest> RoomServiceRequests { get; set; } = new List<RoomServiceRequest>();
}