// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelManagment.Domain.Models;

public partial class Employee
{
    public int EmployeeId { get; set; }

    public string FullName { get; set; }

    public string JobTitle { get; set; }

    public int DepartmentId { get; set; }

    public decimal? Salary { get; set; }

    public string Phone { get; set; }

    public DateOnly? HireDate { get; set; }

    public virtual Department Department { get; set; }

    public virtual ICollection<EmployeeShift> EmployeeShifts { get; set; } = new List<EmployeeShift>();

    public virtual ICollection<MaintenanceRequest> MaintenanceRequests { get; set; } = new List<MaintenanceRequest>();

    public virtual ICollection<RoomServiceRequest> RoomServiceRequests { get; set; } = new List<RoomServiceRequest>();

    public virtual ICollection<User> Users { get; set; } = new List<User>();

    public virtual ICollection<WarehouseItem> WarehouseItems { get; set; } = new List<WarehouseItem>();

    public virtual ICollection<Warehouse> Warehouses { get; set; } = new List<Warehouse>();
}