// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelManagment.Domain.Models;

public partial class FacilityBooking
{
    public int FacilityBookingId { get; set; }

    public int BookingId { get; set; }

    public int FacilityId { get; set; }

    public DateOnly BookingDate { get; set; }

    public TimeOnly StartTime { get; set; }

    public TimeOnly EndTime { get; set; }

    public int Hours { get; set; }

    public decimal? TotalCost { get; set; }

    public string Status { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual Facility Facility { get; set; }
}