// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelManagment.Domain.Models;

public partial class Facility
{
    public int FacilityId { get; set; }

    public string FacilityName { get; set; }

    public string Description { get; set; }

    public decimal? PricePerHour { get; set; }

    public int? Capacity { get; set; }

    public bool IsAvailable { get; set; }

    public virtual ICollection<FacilityBooking> FacilityBookings { get; set; } = new List<FacilityBooking>();
}