// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelManagment.Domain.Models;

public partial class GuestReview
{
    public int ReviewId { get; set; }

    public int BookingId { get; set; }

    public int Rating { get; set; }

    public string Comment { get; set; }

    public DateTime ReviewDate { get; set; }

    public virtual Booking Booking { get; set; }
}