// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelManagment.Domain.Models;

public partial class Guest
{
    public int GuestId { get; set; }

    public string FullName { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string IdPassport { get; set; }

    public string Religion { get; set; }

    public string Nationality { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string Gender { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();
}