// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelManagment.Domain.Models;

public partial class InventoryPerDepartment
{
    public int InventoryId { get; set; }

    public int DepartmentId { get; set; }

    public int WarehouseId { get; set; }

    public int ItemId { get; set; }

    public int Quantity { get; set; }

    public int? MinimumQuantity { get; set; }

    public DateOnly LastUpdated { get; set; }

    public string Notes { get; set; }

    public virtual Department Department { get; set; }

    public virtual Item Item { get; set; }

    public virtual Warehouse Warehouse { get; set; }
}