// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelManagment.Domain.Models;

public partial class Item
{
    public int ItemId { get; set; }

    public string ItemName { get; set; }

    public string ItemType { get; set; }

    public string Unit { get; set; }

    public string Description { get; set; }

    public string Barcode { get; set; }

    public decimal? CostPerUnit { get; set; }

    public string Supplier { get; set; }

    public int? MinimumQuantity { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<InventoryPerDepartment> InventoryPerDepartments { get; set; } = new List<InventoryPerDepartment>();

    public virtual ICollection<WarehouseItem> WarehouseItems { get; set; } = new List<WarehouseItem>();
}