// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelManagment.Domain.Models;

public partial class MaintenanceRequest
{
    public int RequestId { get; set; }

    public int RoomId { get; set; }

    public string Description { get; set; }

    public DateOnly RequestDate { get; set; }

    public string Status { get; set; }

    public int? AssignedEmployeeId { get; set; }

    public string Priority { get; set; }

    public DateOnly? CompletedDate { get; set; }

    public virtual Employee AssignedEmployee { get; set; }

    public virtual Room Room { get; set; }
}