// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelManagment.Domain.Models;

public partial class MenuItem
{
    public int ItemId { get; set; }

    public string ItemName { get; set; }

    public decimal Price { get; set; }

    public string Category { get; set; }

    public bool IsAvailable { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}