// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelManagment.Domain.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public int BookingId { get; set; }

    public DateTime OrderDate { get; set; }

    public decimal? Total { get; set; }

    public string Status { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}