// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelManagment.Domain.Models;

public partial class Room
{
    public int RoomId { get; set; }

    public string RoomNumber { get; set; }

    public int RoomTypeId { get; set; }

    public int Floor { get; set; }

    public string Status { get; set; }

    public string Description { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<MaintenanceRequest> MaintenanceRequests { get; set; } = new List<MaintenanceRequest>();

    public virtual RoomType RoomType { get; set; }
}