// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelManagment.Domain.Models;

public partial class RoomServiceRequest
{
    public int RequestId { get; set; }

    public int BookingId { get; set; }

    public string RequestType { get; set; }

    public string Description { get; set; }

    public DateTime RequestTime { get; set; }

    public string Status { get; set; }

    public int? AssignedEmployeeId { get; set; }

    public DateTime? CompletedTime { get; set; }

    public virtual Employee AssignedEmployee { get; set; }

    public virtual Booking Booking { get; set; }
}