// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelManagment.Domain.Models;

public partial class WarehouseItem
{
    public int WarehouseItemId { get; set; }

    public int WarehouseId { get; set; }

    public int ItemId { get; set; }

    public int Quantity { get; set; }

    public int? MinimumQuantity { get; set; }

    public int? MaximumQuantity { get; set; }

    public DateTime LastUpdated { get; set; }

    public int? LastUpdatedBy { get; set; }

    public string LocationInWarehouse { get; set; }

    public string Notes { get; set; }

    public virtual Item Item { get; set; }

    public virtual Employee LastUpdatedByNavigation { get; set; }

    public virtual Warehouse Warehouse { get; set; }
}