// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HotelManagment.Domain.Models;

public partial class Warehouse
{
    public int WarehouseId { get; set; }

    public string WarehouseName { get; set; }

    public string Location { get; set; }

    public string Description { get; set; }

    public int? Capacity { get; set; }

    public int? ManagerEmployeeId { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<InventoryPerDepartment> InventoryPerDepartments { get; set; } = new List<InventoryPerDepartment>();

    public virtual Employee ManagerEmployee { get; set; }

    public virtual ICollection<WarehouseItem> WarehouseItems { get; set; } = new List<WarehouseItem>();
}